# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
# The vendor BSP stores inverse NEC command bytes. These are normalized Linux
# scancodes for its 0x80, 0x01, and 0x88 remote addresses.

[[protocols]]
name = "Vontar DQ08 remotes"
protocol = "nec"
variant = "nec"

[protocols.scancodes]
0x8013 = "KEY_REPLY"
0x8027 = "KEY_BACK"
0x8038 = "KEY_UP"
0x8040 = "KEY_DOWN"
0x8037 = "KEY_LEFT"
0x8039 = "KEY_RIGHT"
0x8073 = "KEY_HOME"
0x8087 = "KEY_VOLUMEUP"
0x8089 = "KEY_VOLUMEDOWN"
0x8081 = "KEY_POWER"
0x8083 = "KEY_MENU"
0x8048 = "KEY_TEXT"

0x0113 = "KEY_REPLY"
0x0119 = "KEY_BACK"
0x0116 = "KEY_UP"
0x011a = "KEY_DOWN"
0x0151 = "KEY_LEFT"
0x0150 = "KEY_RIGHT"
0x0111 = "KEY_HOME"
0x0118 = "KEY_VOLUMEUP"
0x0110 = "KEY_VOLUMEDOWN"
0x0140 = "KEY_POWER"
0x0141 = "KEY_MUTE"
0x014c = "KEY_MENU"
0x0100 = "KEY_TEXT"
0x014e = "KEY_1"
0x010d = "KEY_2"
0x010c = "KEY_3"
0x014a = "KEY_4"
0x0109 = "KEY_5"
0x0108 = "KEY_6"
0x0146 = "KEY_7"
0x0105 = "KEY_8"
0x0104 = "KEY_9"
0x0101 = "KEY_0"
0x0142 = "KEY_BACKSPACE"
0x0143 = "KEY_SETUP"
0x010f = "KEY_F13"
0x014b = "KEY_PREVIOUS"
0x014f = "KEY_NEXT"
0x0192 = "KEY_KATAKANA"
0x0193 = "KEY_HIRAGANA"
0x01cc = "KEY_HENKAN"
0x018e = "KEY_KATAKANAHIRAGANA"
0x018f = "KEY_MUHENKAN"
0x01c8 = "KEY_KPJPCOMMA"

0x8819 = "KEY_REPLY"
0x8848 = "KEY_BACK"
0x8815 = "KEY_UP"
0x8816 = "KEY_DOWN"
0x8817 = "KEY_LEFT"
0x8818 = "KEY_RIGHT"
0x8847 = "KEY_HOME"
0x8823 = "KEY_VOLUMEUP"
0x8824 = "KEY_VOLUMEDOWN"
0x8821 = "KEY_POWER"
0x8825 = "KEY_MUTE"
0x8860 = "KEY_MENU"
0x8832 = "KEY_TEXT"
0x880f = "KEY_SETUP"
0x8874 = "KEY_F13"
0x8833 = "KEY_PREVIOUS"
0x8834 = "KEY_NEXT"
0x8864 = "KEY_F6"
0x8863 = "KEY_F8"
0x8867 = "KEY_F4"
0x8868 = "KEY_F5"
